In [23]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('spam - spam.csv')
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will �_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [3]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
3637,spam,Customer service announcement. We recently tri...,NaN,NaN,NaN
3631,ham,Oooh I got plenty of those!,NaN,NaN,NaN
2210,ham,Just wanted to say holy shit you guys weren't ...,NaN,NaN,NaN
4256,spam,important information 4 orange user . today is...,NaN,NaN,NaN
4447,ham,I sent them. Do you like?,NaN,NaN,NaN

In [4]:
df.shape

(5572, 5)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 677.1 KB

In [6]:
df=df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])

In [7]:
df.sample(5)

        v1                                                 v2
2363  spam  Fantasy Football is back on your TV. Go to Sky...
5397   ham                      That's necessarily respectful
1806  spam  Todays Voda numbers ending 1225 are selected t...
2541   ham    I dont. Can you send it to me. Plus how's mode.
4368   ham                                     Anytime lor...

In [8]:
df.rename(columns={'v1':'target','v2':'text'},inplace=True)
df.sample(5)

     target                                               text
3516    ham  So you think i should actually talk to him? No...
2337    ham  Tell your friends what you plan to do on Valen...
3818    ham  sorry brah, just finished the last of my exams...
1897    ham  Aight, sounds good. When do you want me to com...
1139    ham  Message:some text missing* Sender:Name Missing...

In [9]:
df

     target                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will �_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [11]:
df['target'] = encoder.fit_transform(df['target'])

In [12]:
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [13]:
df.isnull().sum()

target    0
text      0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(409)

In [15]:
df = df.drop_duplicates(keep='first')

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.shape

(5163, 2)

In [18]:
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [19]:
df['target'].value_counts()

target
0    4516
1     647
Name: count, dtype: int64

In [11]:
import matplotlib.pyplot as plt
plt.pie(df['target'].value_counts(),labels=['ham','spam'],autopct="%0.2f")
plt.show()

KeyError: 'target'

In [21]:
import nltk

In [22]:
%pip install nltk --break-system-packages

Requirement already satisfied: nltk in C:\Users\GAURAV DAS\anaconda3\Lib\site-packages (3.10.0)
Requirement already satisfied: defusedxml in C:\Users\GAURAV DAS\anaconda3\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\GAURAV DAS\anaconda3\Lib\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in C:\Users\GAURAV DAS\anaconda3\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\GAURAV DAS\anaconda3\Lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\GAURAV DAS\anaconda3\Lib\site-packages (from nltk) (4.68.2)
Requirement already satisfied: colorama in C:\Users\GAURAV DAS\anaconda3\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\GAURAV
[nltk_data]     DAS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [12]:
df['num_characters'] = df['text'].apply(len)
df.head()

KeyError: 'text'

In [13]:
import nltk
nltk.download('punkt_tab')
df['num_words'] = df['text'].apply(lambda x:len(nltk.word_tokenize(x)))
df.head()

[nltk_data] Downloading package punkt_tab to C:\Users\GAURAV
[nltk_data]     DAS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

KeyError: 'text'

In [14]:
df['num_sentences'] = df['text'].apply(lambda x:len(nltk.sent_tokenize(x)))
df.head()

KeyError: 'text'

In [15]:
df[['num_characters','num_words','num_sentences']].describe()

KeyError: "None of [Index(['num_characters', 'num_words', 'num_sentences'], dtype='str')] are in the [columns]"

In [16]:
#ham
df[df['target']==0][['num_characters','num_words','num_sentences']].describe()

KeyError: 'target'

In [17]:
#spam
df[df['target']==1][['num_characters','num_words','num_sentences']].describe()

KeyError: 'target'

In [18]:
import seaborn as sns

In [19]:
plt.figure(figsize=(12,6))
sns.histplot(df[df['target']==0]['num_characters'],color='green')
sns.histplot(df[df['target']==1]['num_characters'],color='red')

KeyError: 'target'

In [ ]:
plt.figure(figsize=(12,6))
sns.histplot(df[df['target']==0]['num_words'],color='yellow')
sns.histplot(df[df['target']==1]['num_words'],color='red')

In [20]:
plt.figure(figsize=(12,6))
sns.histplot(df[df['target']==0]['num_sentences'],color='blue')
sns.histplot(df[df['target']==1]['num_sentences'],color='red')

KeyError: 'target'

In [21]:
sns.pairplot(df,hue='target')

ValueError: No variables found for grid columns.

In [22]:
sns.heatmap(df.corr(numeric_only=True),annot=True)

ValueError: zero-size array to reduction operation fmin which has no identity